#!/usr/bin/env node

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Function to read and parse a markdown file
function processEssayFile(filename) {
  const filePath = path.join(__dirname, '..', '_posts', filename);
  
  if (!fs.existsSync(filePath)) {
    console.error(`File not found: ${filePath}`);
    return null;
  }
  
  const content = fs.readFileSync(filePath, 'utf8');
  const slug = filename.replace(/\.markdown$/, '').replace(/^\d{4}-\d{2}-\d{2}-/, '');
  
  // Parse frontmatter
  const frontmatterRegex = /^---\n([\s\S]*?)\n---\n([\s\S]*)$/;
  const match = content.match(frontmatterRegex);
  
  if (!match) {
    console.error(`Invalid markdown format in ${filename}`);
    return null;
  }
  
  const frontmatter = match[1];
  const markdownContent = match[2];
  
  // Parse frontmatter
  const metadata = {
    title: "",
    date: "",
    categories: [],
    tags: [],
    layout: "post",
    image: ""
  };
  
  const lines = frontmatter.split('\n');
  for (const line of lines) {
    const [key, ...valueParts] = line.split(':');
    if (key && valueParts.length > 0) {
      const value = valueParts.join(':').trim();
      
      switch (key.trim()) {
        case 'title':
          metadata.title = value.replace(/"/g, '');
          break;
        case 'date':
          metadata.date = value;
          break;
        case 'categories':
          const categoriesMatch = value.match(/\[(.*)\]/);
          if (categoriesMatch) {
            metadata.categories = categoriesMatch[1].split(',').map(cat => cat.trim());
          }
          break;
        case 'tags':
          const tagsMatch = value.match(/\[(.*)\]/);
          if (tagsMatch) {
            metadata.tags = tagsMatch[1].split(',').map(tag => tag.trim());
          }
          break;
        case 'layout':
          metadata.layout = value;
          break;
        case 'image':
          metadata.image = value.replace(/"/g, '');
          break;
      }
    }
  }
  
  // Escape the content for JavaScript string
  const escapedContent = markdownContent
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$/g, '\\$');
  
  return {
    metadata,
    content: escapedContent,
    slug
  };
}

// Function to generate the essayLoader.ts file
function generateEssayLoader(essays) {
  const template = `import { parseMarkdownFile, Essay } from './markdown';

// Build-time processed essays
// This file is auto-generated by scripts/process-essays.js
const essays: Essay[] = [
${essays.map(essay => `  {
    metadata: {
      title: "${essay.metadata.title}",
      date: "${essay.metadata.date}",
      categories: [${essay.metadata.categories.map(cat => `"${cat}"`).join(', ')}],
      tags: [${essay.metadata.tags.map(tag => `"${tag}"`).join(', ')}],
      layout: "${essay.metadata.layout}",
      image: "${essay.metadata.image}"
    },
    content: \`${essay.content}\`,
    slug: "${essay.slug}"
  }`).join(',\n')}
];

// Create a map for fast lookup by slug
const essayMap = new Map<string, Essay>();
essays.forEach(essay => {
  essayMap.set(essay.slug, essay);
});

export async function getEssay(slug: string): Promise<Essay | null> {
  // Simulate async behavior for consistency
  await new Promise(resolve => setTimeout(resolve, 10));
  return essayMap.get(slug) || null;
}

export async function getAllEssays(): Promise<Essay[]> {
  // Simulate async behavior for consistency
  await new Promise(resolve => setTimeout(resolve, 10));
  
  // Sort by date (newest first)
  return [...essays].sort((a, b) => 
    new Date(b.metadata.date).getTime() - new Date(a.metadata.date).getTime()
  );
}

// Clear cache (not needed for this approach, but keeping for API consistency)
export function clearEssayCache(): void {
  // No cache to clear in this approach
}
`;

  return template;
}

// Helper to extract CSS links from dist/index.html
function getCssLinksFromDist() {
  const distIndexPath = path.join(__dirname, '..', 'dist', 'index.html');
  if (!fs.existsSync(distIndexPath)) return '';
  const html = fs.readFileSync(distIndexPath, 'utf8');
  // Match all <link rel="stylesheet" ...> tags
  const matches = html.match(/<link rel="stylesheet"[^>]*>/g);
  return matches ? matches.join('\n    ') : '';
}

// Static navbar HTML (converted from React component)
function getNavbarHtml() {
  return `<header class="fixed top-0 left-0 right-0 z-50 transition-all duration-300 bg-white shadow-md py-3">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex items-center justify-between">
      <div class="flex-shrink-0">
        <a href="/" class="font-semibold text-xl text-dark-red">Home</a>
      </div>

      <!-- Desktop navigation -->
      <nav class="hidden md:flex space-x-8">
        <a href="/initiatives" class="font-medium transition-colors text-charcoal/80 hover:text-charcoal">Initiatives & Ventures</a>
        <a href="/advisory" class="font-medium transition-colors text-charcoal/80 hover:text-charcoal">Advisory & Board Roles</a>
        <a href="/research" class="font-medium transition-colors text-charcoal/80 hover:text-charcoal">Research Projects</a>
        <a href="/essays" class="font-medium transition-colors text-accent-blue">Essays</a>
        <a href="/book" class="font-medium transition-colors text-charcoal/80 hover:text-charcoal">Book</a>
        <a href="/about" class="font-medium transition-colors text-charcoal/80 hover:text-charcoal">About Me</a>
      </nav>

      <div class="hidden md:block">
        <a href="/#contact" class="bg-dark-red hover:bg-dark-red/90 text-white px-4 py-2 rounded-lg font-medium transition-colors">Get in Touch</a>
      </div>

      <!-- Mobile menu button -->
      <div class="md:hidden flex items-center">
        <button class="text-charcoal focus:outline-none" aria-label="Toggle menu">
          <svg class="h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>
          </svg>
        </button>
      </div>
    </div>
  </div>
</header>`;
}

// Static footer HTML (converted from React component)
function getFooterHtml() {
  const currentYear = new Date().getFullYear();
  return `<footer class="bg-charcoal py-12">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="md:flex md:items-center md:justify-between">
      <div class="space-y-4 md:space-y-6">
        <h3 class="text-lg font-medium text-white">Claus Horn</h3>
        <p class="text-sm text-white/70 max-w-md">
          Scientist and AI entrepreneur <br />
          - accelerating science with AI.
        </p>
      </div>
      
      <div class="mt-8 md:mt-0">
        <h4 class="text-sm font-semibold text-white mb-3">Connect</h4>
        <div class="flex space-x-3">
          <a href="mailto:claus@claushorn.com" class="text-white/70 hover:text-white transition-colors" aria-label="Email">
            <svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 8l7.89 4.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"></path>
            </svg>
          </a>
          <a href="#" class="text-white/70 hover:text-white transition-colors" aria-label="LinkedIn">
            <svg class="h-5 w-5" fill="currentColor" viewBox="0 0 24 24">
              <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/>
            </svg>
          </a>
          <a href="#" class="text-white/70 hover:text-white transition-colors" aria-label="Website">
            <svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 12a9 9 0 01-9 9m9-9a9 9 0 00-9-9m9 9H3m9 9a9 9 0 01-9-9m9 9c1.657 0 3-4.03 3-9s-1.343-9-3-9m0 18c-1.657 0-3-4.03-3-9s1.343-9 3-9m-9 9a9 9 0 019-9"></path>
            </svg>
          </a>
        </div>
      </div>
    </div>
    
    <div class="mt-8 pt-8 border-t border-white/20 md:flex md:items-center md:justify-between">
      <p class="text-sm text-white/60">&copy; ${currentYear} Claus Horn. All rights reserved.</p>
      <div class="mt-4 md:mt-0">
        <p class="text-sm text-white/60">Based in Switzerland and New Haven • Available globally</p>
      </div>
    </div>
  </div>
</footer>`;
}

// Function to generate a static HTML file for an essay
function generateEssayHtml(essay) {
  const { title, date, image } = essay.metadata;
  const htmlContent = convertMarkdownToHtml(essay.content);
  const cssLinks = getCssLinksFromDist();
  return `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/x-icon" href="/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${title} | Claus Horn</title>
    <meta name="description" content="${title} - Essay by Claus Horn" />
    ${cssLinks}
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" />
  </head>
  <body class="bg-white text-charcoal font-sans">
    ${getNavbarHtml()}
    <main class="pt-20">
      <article class="pt-8 pb-20">
        <div class="section-container max-w-4xl mx-auto">
          <header class="mb-12">
            <div class="flex items-center space-x-4 text-sm text-charcoal/60 mb-6">
              <span>${new Date(date).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</span>
            </div>
            <h1 class="text-4xl md:text-5xl font-bold text-charcoal mb-6">${title}</h1>
            ${image ? `<div class="mb-8"><img src="/images/${image}" alt="${title}" class="w-full max-w-2xl h-48 object-cover rounded-lg" /></div>` : ''}
          </header>
          <div class="prose prose-lg max-w-none">${htmlContent}</div>
        </div>
      </article>
    </main>
    ${getFooterHtml()}
  </body>
</html>`;
}

// Copy of convertMarkdownToHtml from src/utils/markdown.ts
function convertMarkdownToHtml(markdown) {
  let html = markdown;
  html = html.replace(/^### (.*$)/gim, '<h3 class="text-xl font-semibold text-charcoal mb-4">$1</h3>');
  html = html.replace(/^## (.*$)/gim, '<h2 class="text-2xl font-semibold text-charcoal mb-6">$1</h2>');
  html = html.replace(/^# (.*$)/gim, '<h1 class="text-3xl font-bold text-charcoal mb-8">$1</h1>');
  html = html.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');
  html = html.replace(/\*([^*]*?)\*/gs, '<em>$1</em>');
  html = html.replace(/```([\s\S]*?)```/g, '<pre class="bg-light-gray p-4 rounded-lg overflow-x-auto mb-4"><code>$1</code></pre>');
  html = html.replace(/`(.*?)`/g, '<code class="bg-light-gray px-1 py-0.5 rounded text-sm">$1</code>');
  html = html.replace(/\[([^\]]+)\]\(([^)]+)\)/g, (match, text, url) => {
    const isInternal = url.startsWith('#') || url.startsWith('/');
    const target = isInternal ? '' : 'target="_blank"';
    const rel = isInternal ? '' : 'rel="noopener noreferrer"';
    return `<a href="${url}" class="text-accent-blue hover:text-dark-red underline" ${target} ${rel}>${text}</a>`;
  });
  html = html.replace(/\[(\d+)\]/g, '<a href="#ref-$1" class="text-accent-blue hover:text-dark-red underline">[$1]</a>');
  html = html.replace(/^\* (.*$)/gim, '<li class="ml-4 mb-2">$1</li>');
  html = html.replace(/(<li.*<\/li>)/s, '<ul class="list-disc ml-6 mb-4">$1</ul>');
  html = html.replace(/^(?!<[h|u|o|p|li])(.*$)/gim, '<p class="text-charcoal/80 leading-relaxed mb-4">$1</p>');
  html = html.replace(/<p class="text-charcoal\/80 leading-relaxed mb-4"><\/p>/g, '<div class="h-4"></div>');
  return html;
}

// Main function
function main() {
  const postsDir = path.join(__dirname, '..', '_posts');
  
  if (!fs.existsSync(postsDir)) {
    console.log('Creating _posts directory...');
    fs.mkdirSync(postsDir, { recursive: true });
  }
  
  const files = fs.readdirSync(postsDir)
    .filter(file => file.endsWith('.markdown'))
    .sort((a, b) => b.localeCompare(a)); // Sort newest first
  
  console.log(`Found ${files.length} essay files:`);
  files.forEach(file => console.log(`  - ${file}`));
  
  const essays = [];
  
  for (const filename of files) {
    const essay = processEssayFile(filename);
    if (essay) {
      essays.push(essay);
      console.log(`✅ Processed: ${essay.metadata.title}`);
    }
  }
  
  if (essays.length === 0) {
    console.log('No essays found. Creating a sample essay...');
    const sampleEssay = {
      metadata: {
        title: "Sample Essay",
        date: "2025-01-01",
        categories: ["Sample"],
        tags: ["Sample"],
        layout: "post"
      },
      content: "This is a sample essay. Add your own essays to the _posts directory.",
      slug: "sample"
    };
    essays.push(sampleEssay);
  }
  
  // Generate the essayLoader.ts file
  const loaderContent = generateEssayLoader(essays);
  const loaderPath = path.join(__dirname, '..', 'src', 'utils', 'essayLoader.ts');
  
  fs.writeFileSync(loaderPath, loaderContent);
  console.log(`\n✅ Generated essayLoader.ts with ${essays.length} essays`);
  console.log(`📝 Essays are now available in your app!`);

  // Generate static HTML files for each essay
  const distEssaysDir = path.join(__dirname, '..', 'dist', 'essays');
  if (!fs.existsSync(distEssaysDir)) {
    fs.mkdirSync(distEssaysDir, { recursive: true });
  }
  essays.forEach(essay => {
    const essayDir = path.join(distEssaysDir, essay.slug);
    if (!fs.existsSync(essayDir)) {
      fs.mkdirSync(essayDir, { recursive: true });
    }
    const html = generateEssayHtml(essay);
    fs.writeFileSync(path.join(essayDir, 'index.html'), html);
    console.log(`✅ Generated static HTML for essay: ${essay.slug}`);
  });

  // Copy 404.html for GitHub Pages SPA routing
  const public404 = path.join(__dirname, '..', 'public', '404.html');
  const dist404 = path.join(__dirname, '..', 'dist', '404.html');
  if (fs.existsSync(public404)) {
    fs.copyFileSync(public404, dist404);
    console.log('✅ Copied 404.html for GitHub Pages SPA routing');
  }
}

main(); 